Traceback (most recent call last):
  File "/Users/robinkoestler/opt/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/robinkoestler/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/robinkoestler/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/robinkoestler/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/robinkoestler/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/robinkoestler/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/Users/robinkoestler/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/robinkoestler/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
N = 10**4
for k in range(3,9):
    p = 2*scipy.stats.norm(0,1).cdf((k + 0.5)) - 1
    print(f"k = {k} leads to 1-{N}*(1-p) = {1-N*(1-p)}")
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m/var/folders/p2/yh1s76w93515jchmc8s5slgm0000gn/T/ipykernel_8490/3349666160.py[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0mN[0m [0;34m=[0m [0;36m10[0m[0;34m**[0m[0;36m4[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0;32mfor[0m [0mk[0m [0;32min[0m [0mrange[0m[0;34m([0m[0;36m3[0m[0;34m,[0m[0;36m9[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 3[0;31m     [0mp[0m [0;34m=[0m [0;36m2[0m[0;34m*[0m[0mscipy[0m[0;34m.[0m[0mstats[0m[0;34m.[0m[0mnorm[0m[0;34m([0m[0;36m0[0m[0;34m,[0m[0;36m1[0m[0;34m)[0m[0;34m.[0m[0mcdf[0m[0;34m([0m[0;34m([0m[0mk[0m [0;34m+[0m [0;36m0.5[0m[0;34m)[0m[0;34m)[0m [0;34m-[0m [0;36m1[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      4[0m     [0mprint[0m[0;34m([0m[0;34mf"k = {k} leads to 1-{N}*(1-p) = {1-N*(1-p)}"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'scipy' is not defined
NameError: name 'scipy' is not defined

